apiVersion: v2
name: solr
version: 3.2.0
appVersion: 8.7.0
description: "A helm chart to install Apache Solr: http://lucene.apache.org/solr/"
keywords:
  - solr
  - lucene
  - web
  - index
home: https://github.com/PreferredAI/helm-charts/tree/master/charts/solr
sources:
  - https://github.com/apache/lucene-solr
  - https://github.com/docker-solr/docker-solr
  - https://github.com/bitnami/charts
icon: https://pbs.twimg.com/profile_images/532569454266179584/al3IkKF8_400x400.png
dependencies:
  - name: common
    version: 1.3.4
    repository: https://charts.bitnami.com/bitnami
  - name: zookeeper
    version: 5.23.0
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - email: lwj5@hotmail.com
    name: lwj5
