## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##
global: {}
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Docker Official Solr image version
## ref: https://hub.docker.com/_/solr/
##
image:
  registry: docker.io
  repository: solr
  tag: 8.7.0
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecrets:

## String to partially override solr.fullname template (will maintain the release name)
##
nameOverride:

## String to fully override solr.fullname template
##
fullnameOverride:

## Solr settings
##
port: 8983

# Settings for solr java memory
javaMem: "-Xms2g -Xmx3g"

## Specify '.sh' scripts the initial scripts here to be executed before starting Solr
## You must use this with extraVolumeMounts and extraVolumes.
##
## initScripts:
##   enable-basicauth.sh: |
##     #!/bin/bash
##     solr zk ls / | (! grep -wq security.json) && solr zk cp file:path_to_local_security.json zk:/security.json
##   do-something-else.sh: |
##     #!/bin/bash
##     echo "Do do-something-else.sh"
##
initScripts: {}

## Extra volumes to add to the deployment such as configmaps
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
##
## extraVolumes:
##   - name: init-scripts
##     configMap:
##       # Provide the name of the ConfigMap containing the files you want
##       # to add to the container
##       name: solr-init-scripts
extraVolumes: []

## Extra volume mounts to add to the container
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
##
## extraVolumeMounts:
##   - name: init-scripts
##     mountPath: /docker-entrypoint-initdb.d
extraVolumeMounts: []

# Sets the termination Grace period for the solr pods
# This can take a while for shards to elect new leaders
terminationGracePeriodSeconds: 180

# The log level of the Solr instances
logLevel: "INFO"

# Solr pod disruption budget
podDisruptionBudget:
  maxUnavailable: 1

## Number of replicas
##
replicaCount: 3
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi
## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## updateStrategy for Solr
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
##
updateStrategy:
  type: RollingUpdate
## An array to add extra env vars
## For example:
## extraEnvVars:
##  - name: KIBANA_ELASTICSEARCH_URL
##    value: test
##
extraEnvVars:
## Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}
## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
volumeClaimTemplates:
  ## solr data Persistent Volume Storage Class
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  ## PersistentVolumeClaim size
  ##
  storageSize: 20Gi

## Use an existing PersistentVolumeClaim
## For example: Share a volume between the pods using EFS CSI driver
## ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver
##
existingVolumeClaim: ""

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 8983
  runAsUser: 8983
  runAsNonRoot: true

## Kubernetes service type
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
## Set this to NodePort, LoadBalancer or ClusterIP
##
service:
  ## Service type
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  ##
  type: ClusterIP
  ## HTTP Port
  ##
  port: 8983
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: ""
  ## Service clusterIP.
  ##
  # clusterIP: None
  ## Specify the loadBalancerIP value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  ##
  # loadBalancerIP:
  ## Specify the loadBalancerSourceRanges value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  loadBalancerSourceRanges: []
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## Additional service annotations (evaluate as a template)
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  annotations: {}

## Configure the ingress resource that allows you to access the panel
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: false

  ## Set this to true in order to add the corresponding annotations for cert-manager
  ##
  certManager: false

  ## Ingress Path type
  ##
  pathType: ImplementationSpecific

  ## Override API Version (automatically detected if not set)
  ##
  apiVersion:

  ## When the ingress is enabled, a host pointing to this will be created
  ##
  hostname: solr.local

  ## The Path to Solr. You may need to set this to '/*' in order to use this
  ## with ALB ingress controllers.
  ##
  path: /

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  ##
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  ##
  annotations: {}

  ## Enable TLS configuration for the hostname defined at ingress.hostname parameter
  ## TLS certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.ingress.hostname }}
  ## You can use the ingress.secrets parameter to create this TLS secret or relay on cert-manager to create it
  ##
  tls: false

  ## The list of additional hostnames to be covered with this ingress record.
  ## Most likely the hostname above will be enough, but in the event more hosts are needed, this is an array
  ## extraHosts:
  ## - name: solr.local
  ##   path: /
  ##

  ## Any additional arbitrary paths that may need to be added to the ingress under the main host.
  ## For example: The ALB ingress controller requires a special rule for handling SSL redirection.
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
  ##

  ## The tls configuration for additional hostnames to be covered with this ingress record.
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## extraTls:
  ## - hosts:
  ##     - solr.local
  ##   secretName: solr.local-tls
  ##

  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ##
  secrets: []
  ## - name: solr.local-tls
  ##   key:
  ##   certificate:
  ##

## Configure extra options for liveness and readiness probes
## This applies to all the Solr in the sharded cluster
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
##
livenessProbe:
  enabled: true
  useSocket: false
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  useSocket: false
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Configuration for solr TLS handling, see README.md for more instructions
tls:
  enabled: false
  wantClientAuth: "false"
  needClientAuth: "false"
  keystorePassword: "changeit"
  importKubernetesCA: "false"
  checkPeerName: "false"
  caSecret:
    name: ""
    bundlePath: ""
  certSecret:
    name: ""
    keyPath: "tls.key"
    certPath: "tls.crt"

# Configuration for the solr prometheus exporter
exporter:
  image: {}
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  #   pullSecrets:
  #     - myRegistryKeySecretName
  # Deploy the exporter
  enabled: false
  # The config file to point the exporter to
  configFile: "/opt/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml"
  updateStrategy: {}
  # Annotations to apply to the exporter pod
  podAnnotations: {}
  # Resource limits for the exporter
  resources: {}
  # The port to run the exporter on
  port: 9983
  # The number of threads the exporter uses to query solr
  threads: 7
  # Liveness configuration for exporter pod
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
  # Readiness configuration for exporter pod
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
  service:
    type: "ClusterIP"
    annotations: {}

zookeeper:
  replicaCount: 3
  fourlwCommandsWhitelist: "srvr, mntr, ruok, conf"
